version: 2

multi-ecosystem-groups:
    infrastructure:
        schedule:
            interval: "friday"

updates:
    - package-ecosystem: "composer"
      directory: "/"
      patterns:
          - "*"
      multi-ecosystem-group: "infrastructure"

    - package-ecosystem: "bun"
      directory: "/"
      patterns:
          - "*"
      multi-ecosystem-group: "infrastructure"
