version: 2

multi-ecosystem-groups:
    all-dependencies-group:
        schedule:
            interval: "weekly"
            day: "friday"
        patterns:
            - "*"

updates:
    - package-ecosystem: "composer"
      directory: "/"
      multi-ecosystem-group: "all-dependencies-group"

    - package-ecosystem: "bun"
      directory: "/"
      multi-ecosystem-group: "all-dependencies-group"
